env:
  browser: true
  node: true

parser: babel-eslint

extends:
  - airbnb-base
  - prettier

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/features/**/*.js'
